add_rules("mode.debug", "mode.release")
set_languages("c++17")
add_requires("gflags", "brpc", "glog", "nlohmann_json")

target("tracker")
    set_kind("binary")
    add_packages("gflags")
    add_packages("glog")
    add_packages("brpc")
    add_packages("nlohmann_json")
    -- add_linkdirs("/lib64")
    add_rules("c++")
    add_rules("protobuf.cpp")
    add_files("tracker.cc")
